# Generated by Django 5.2.8 on 2025-12-09 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(default='(주)퍼시픽프라우드', max_length=50, verbose_name='예금주')),
                ('initial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='기초 잔액')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 중')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='우리회사', max_length=100)),
                ('biz_number', models.CharField(blank=True, max_length=20)),
                ('ceo_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('department', models.CharField(default='물류팀', max_length=50)),
                ('join_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명')),
                ('partner_type', models.CharField(choices=[('SUPPLIER', '매입처'), ('CLIENT', '매출처'), ('BOTH', '혼합')], max_length=10, verbose_name='구분')),
                ('biz_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='대표자명')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표 전화번호')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자명')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자 연락처')),
                ('initial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='기초 미수/미지급금')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SEAFOOD', '수산물'), ('MEAT', '육류'), ('LIQUOR', '주류'), ('INDUSTRIAL', '공산품'), ('DAILY', '생필품'), ('VEGETABLE', '농산물')], default='SEAFOOD', max_length=20)),
                ('storage_type', models.CharField(choices=[('DRY', '상온 (Dry)'), ('COLD', '냉장 (Cold)'), ('FROZEN', '냉동 (Frozen)'), ('LIVE_TANK', '활어 수조 (Live Tank)')], max_length=20)),
                ('unit', models.CharField(default='EA', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shelf_life_days', models.IntegerField(default=7)),
                ('is_taxable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storage_type', models.CharField(choices=[('DRY', '상온 (Dry)'), ('COLD', '냉장 (Cold)'), ('FROZEN', '냉동 (Frozen)'), ('LIVE_TANK', '활어 수조 (Live Tank)')], default='DRY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='지출일자')),
                ('category', models.CharField(choices=[('PURCHASE', '물품대금 (매입)'), ('SALARY', '급여/인건비'), ('RENT', '임차료'), ('UTILITY', '수도광열비 (전기/수도)'), ('LOGISTICS', '운반비/물류비'), ('MEAL', '복리후생비 (식대 등)'), ('TAX', '세금과공과'), ('ETC', '기타 잡비')], max_length=20, verbose_name='계정과목')),
                ('description', models.CharField(max_length=100, verbose_name='적요 (내용)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='지출금액')),
                ('has_proof', models.BooleanField(default=True, verbose_name='적격증빙 유무')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.bankaccount', verbose_name='출금 계좌')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='거래일')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAWAL', '출금')], max_length=20, verbose_name='구분')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='금액')),
                ('description', models.CharField(max_length=100, verbose_name='적요')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fulfillment.bankaccount', verbose_name='계좌')),
                ('related_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_trx', to='fulfillment.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', '접수'), ('ALLOCATED', '피킹지시'), ('SHIPPED', '출고완료')], default='PENDING', max_length=20)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_cogs', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('client', models.ForeignKey(limit_choices_to={'partner_type__in': ['CLIENT', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='거래일자')),
                ('payment_type', models.CharField(choices=[('INBOUND', '수금 (입금)'), ('OUTBOUND', '지급 (출금)')], max_length=10, verbose_name='구분')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('method', models.CharField(choices=[('CASH', '현금'), ('BANK', '계좌이체'), ('CARD', '카드')], default='CASH', max_length=20, verbose_name='결제수단')),
                ('memo', models.CharField(blank=True, max_length=100, verbose_name='적요')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.bankaccount', verbose_name='연동 계좌')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.partner', verbose_name='거래처')),
                ('related_bank_trx', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('month_label', models.CharField(max_length=20)),
                ('base_pay', models.DecimalField(decimal_places=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('leave_pay', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.employee')),
                ('related_expense', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.expense')),
            ],
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_qty', models.IntegerField()),
                ('picked', models.BooleanField(default=False)),
                ('picked_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_lists', to='fulfillment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('supplied_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ORDERED', '발주됨'), ('RECEIVED', '입고완료')], default='ORDERED', max_length=20)),
                ('is_bill_published', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(limit_choices_to={'partner_type__in': ['SUPPLIER', 'BOTH']}, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.purchase')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.location')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.employee')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fulfillment.zone'),
        ),
    ]
