# Generated by Django 5.2.8 on 2025-11-29 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='위치 코드')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명')),
                ('partner_type', models.CharField(choices=[('SUPPLIER', '매입처 (공급사)'), ('CLIENT', '매출처 (납품처)'), ('BOTH', '매입/매출 혼합')], max_length=10, verbose_name='구분')),
                ('biz_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='대표자명')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='미수/미지급 잔액')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('category', models.CharField(choices=[('SEAFOOD', '수산물 (생물/냉동)'), ('MEAT', '육류 (정육/가공)'), ('LIQUOR', '주류'), ('INDUSTRIAL', '공산/가공품'), ('DAILY', '생필품 (휴지/세제)'), ('VEGETABLE', '농산물')], default='SEAFOOD', max_length=20, verbose_name='카테고리')),
                ('storage_type', models.CharField(choices=[('DRY', '상온 (Dry)'), ('COLD', '냉장 (Cold)'), ('FROZEN', '냉동 (Frozen)'), ('LIVE_TANK', '활어 수조 (Live Tank)')], max_length=20, verbose_name='보관타입')),
                ('unit', models.CharField(default='EA', max_length=10, verbose_name='단위')),
                ('shelf_life_days', models.IntegerField(default=7, verbose_name='유통기한(일)')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='매입단가(원가)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='판매단가(매가)')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='과세상품여부')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='구역명')),
                ('storage_type', models.CharField(choices=[('DRY', '상온 (Dry)'), ('COLD', '냉장 (Cold)'), ('FROZEN', '냉동 (Frozen)'), ('LIVE_TANK', '활어 수조 (Live Tank)')], default='DRY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', '접수'), ('ALLOCATED', '피킹지시'), ('SHIPPED', '출고완료')], default='PENDING', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 매출액')),
                ('total_cogs', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 원가(COGS)')),
                ('client', models.ForeignKey(limit_choices_to={'partner_type__in': ['CLIENT', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner', verbose_name='납품처')),
            ],
        ),
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_qty', models.IntegerField()),
                ('picked', models.BooleanField(default=False)),
                ('picked_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_lists', to='fulfillment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='주문 수량')),
                ('supplied_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='매입일자')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 매입액')),
                ('status', models.CharField(choices=[('ORDERED', '발주됨'), ('RECEIVED', '입고완료')], default='ORDERED', max_length=20)),
                ('is_bill_published', models.BooleanField(default=False, verbose_name='세금계산서 수취')),
                ('supplier', models.ForeignKey(limit_choices_to={'partner_type__in': ['SUPPLIER', 'BOTH']}, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner', verbose_name='공급사')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fulfillment.zone'),
        ),
    ]
