# Generated by Django 5.2.8 on 2025-11-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='매입 단가')),
                ('expiry_date', models.DateField(verbose_name='유통기한')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.product', verbose_name='매입 상품')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fulfillment.purchase')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.location', verbose_name='적치 위치')),
            ],
        ),
    ]
