# Generated by Django 5.2.8 on 2025-11-29 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='지출일자')),
                ('category', models.CharField(choices=[('SALARY', '급여/인건비'), ('RENT', '임차료'), ('UTILITY', '수도광열비 (전기/수도)'), ('LOGISTICS', '운반비/물류비'), ('MEAL', '복리후생비 (식대 등)'), ('TAX', '세금과공과'), ('ETC', '기타 잡비')], max_length=20, verbose_name='계정과목')),
                ('description', models.CharField(max_length=100, verbose_name='적요 (내용)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='지출금액')),
                ('has_proof', models.BooleanField(default=True, verbose_name='적격증빙 유무')),
            ],
        ),
    ]
