# Generated by Django 5.2.8 on 2025-11-29 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('position', models.CharField(max_length=50, verbose_name='직급')),
                ('department', models.CharField(default='물류팀', max_length=50, verbose_name='부서')),
                ('join_date', models.DateField(verbose_name='입사일')),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='기본급 (VND)')),
                ('is_active', models.BooleanField(default=True, verbose_name='재직 여부')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='지급일')),
                ('month_label', models.CharField(max_length=20, verbose_name='귀속월 (예: 2025-11)')),
                ('base_pay', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='기본급')),
                ('overtime_pay', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='초과근무수당')),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='보너스/식대')),
                ('deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='공제액(세금/보험)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='실수령액')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.employee', verbose_name='직원')),
                ('related_expense', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.expense')),
            ],
        ),
    ]
