# Generated by Django 5.2.8 on 2025-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0005_remove_partner_balance_partner_initial_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자명'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자 연락처'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='biz_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='initial_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='기초 미수/미지급금'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='상호명'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='대표자명'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('SUPPLIER', '매입처'), ('CLIENT', '매출처'), ('BOTH', '혼합')], max_length=10, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='대표 전화번호'),
        ),
    ]
