# Generated by Django 5.2.8 on 2025-12-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0006_partner_contact_person_partner_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='우리회사', max_length=100, verbose_name='상호명')),
                ('biz_number', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('ceo_name', models.CharField(blank=True, max_length=50, verbose_name='대표자명')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='사업장 주소')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='대표 전화')),
                ('bank_account', models.CharField(blank=True, help_text='예: 국민은행 000-000-000000', max_length=100, verbose_name='입금 계좌번호')),
            ],
        ),
    ]
