# Generated by Django 5.2.8 on 2025-12-01 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0007_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_pay',
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leave_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='수당(년/월차)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='기본급 (VND)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='물류팀', max_length=50, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='재직 여부'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='성명'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, verbose_name='직급'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_pay',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='기본급'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='성과급'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='차감액(세금/보험)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.employee', verbose_name='직원'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month_label',
            field=models.CharField(max_length=20, verbose_name='귀속월'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='지급일'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='실수령액'),
        ),
    ]
