# Generated by Django 5.2.8 on 2025-12-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0008_remove_payroll_overtime_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주문 메모'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['CLIENT', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner', verbose_name='납품처'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cogs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 원가(COGS)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 매출액'),
        ),
    ]
