# Generated by Django 5.2.8 on 2025-12-02 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0009_order_memo_alter_order_client_alter_order_total_cogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(default='(주)퍼시픽프라우드', max_length=50, verbose_name='예금주')),
                ('initial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='기초 잔액')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 중')),
            ],
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='biz_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='우리회사', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='물류팀', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='지출금액'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('SALARY', '급여/인건비'), ('RENT', '임차료'), ('UTILITY', '수도광열비'), ('LOGISTICS', '운반비'), ('MEAL', '복리후생비'), ('TAX', '세금과공과'), ('ETC', '기타')], max_length=20, verbose_name='계정과목'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='지출일자'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=100, verbose_name='적요 (내용)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='has_proof',
            field=models.BooleanField(default=True, verbose_name='적격증빙 유무'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['CLIENT', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='fulfillment.partner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cogs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='base_pay',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='deduction',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='leave_pay',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month_label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.bankaccount', verbose_name='출금 계좌'),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='거래일')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAWAL', '출금')], max_length=20, verbose_name='구분')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='금액')),
                ('description', models.CharField(max_length=100, verbose_name='적요')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fulfillment.bankaccount', verbose_name='계좌')),
                ('related_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_trx', to='fulfillment.expense')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('issues', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.employee')),
            ],
        ),
    ]
