# Generated by Django 5.2.8 on 2025-12-08 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0010_bankaccount_alter_companyinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.bankaccount', verbose_name='연동 계좌'),
        ),
        migrations.AddField(
            model_name='payment',
            name='related_bank_trx',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.banktransaction'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PURCHASE', '물품대금 (매입)'), ('SALARY', '급여/인건비'), ('RENT', '임차료'), ('UTILITY', '수도광열비 (전기/수도)'), ('LOGISTICS', '운반비/물류비'), ('MEAL', '복리후생비 (식대 등)'), ('TAX', '세금과공과'), ('ETC', '기타 잡비')], max_length=20, verbose_name='계정과목'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='거래일자'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, max_length=100, verbose_name='적요'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', '현금'), ('BANK', '계좌이체'), ('CARD', '카드')], default='CASH', max_length=20, verbose_name='결제수단'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulfillment.partner', verbose_name='거래처'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('INBOUND', '수금 (입금)'), ('OUTBOUND', '지급 (출금)')], max_length=10, verbose_name='구분'),
        ),
    ]
